In [ ]:
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten

In [ ]:
import numpy as np

In [ ]:
test = pd.read_csv('Final_Test.csv')
train = pd.read_csv("Final_Train.csv")

In [ ]:
final = train.drop(['Pediatric' , 'Geriatric' , '15-24' , '25-34' , '35-44' , '45-54' , '55-64' , 'NEP Total' , 'SumOfHIV_infected'] , axis = 1)

In [ ]:
final['NEP Total'] = train['NEP Total']

In [ ]:
final.head()

AGRA  AIZAWL  ALAPPUZHA  ...        no2        rspm  NEP Total
0     1       0          0  ...  23.744767  215.715909        275
1     1       0          0  ...  22.504294  184.648809        391
2     1       0          0  ...  17.422785  136.511628        363
3     1       0          0  ...  27.542857  224.551219        291
4     1       0          0  ...  21.356085  189.052632        378

[5 rows x 89 columns]

In [ ]:
final = final.fillna(method ='bfill') 

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled = scaler.fit_transform(final.values)
scaled_df = pd.DataFrame(scaled , columns = final.columns)

In [ ]:
scaled_df

AGRA  AIZAWL  ALAPPUZHA  ...       no2      rspm  NEP Total
0      1.0     0.0        0.0  ...  0.041652  0.020741   0.157576
1      1.0     0.0        0.0  ...  0.039022  0.017539   0.224242
2      1.0     0.0        0.0  ...  0.028246  0.012578   0.181818
3      1.0     0.0        0.0  ...  0.049707  0.021652   0.218182
4      1.0     0.0        0.0  ...  0.036587  0.017993   0.200000
...    ...     ...        ...  ...       ...       ...        ...
3367   0.0     0.0        0.0  ...  0.028486  0.006297   0.412121
3368   0.0     0.0        0.0  ...  0.034250  0.005970   0.430303
3369   0.0     0.0        0.0  ...  0.035336  0.006500   0.490909
3370   0.0     0.0        0.0  ...  0.035805  0.007190   0.472727
3371   0.0     0.0        0.0  ...  0.035365  0.006755   0.569697

[3372 rows x 89 columns]

In [ ]:
from tensorflow.keras.layers import Dropout , MaxPool1D , LSTM

In [ ]:
model = Sequential()
model.add(Conv1D(32, 2, activation="relu", input_shape=(88, 1)))
model.add(Flatten())
model.add(Dense(64, activation="relu"))
model.add(Dense(1))
model.compile(loss="mse", optimizer="adam")

In [ ]:
X = final.drop('NEP Total' , axis = 1)
y = final['NEP Total']

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scalerX = MinMaxScaler()
scaledX = scalerX.fit_transform(X.values)
scaledX_df = pd.DataFrame(scaledX , columns = X.columns)

In [ ]:
y_arr = np.array(y)

In [ ]:
y_arr = y_arr.reshape(1 , -1)

In [ ]:
y_arr

array([[275, 391, 363, ..., 431, 460, 470]])

In [ ]:
scalerY = MinMaxScaler()

In [ ]:
scaled_y = scalerY.fit_transform(final['NEP Total'].values.reshape(-1,1))

In [ ]:
scaled_y

array([[0.26871795],
       [0.38769231],
       [0.35897436],
       ...,
       [0.42871795],
       [0.45846154],
       [0.46871795]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(scaledX_df, scaled_y, test_size=0.20, random_state=42)

In [ ]:
x = X_train.values

In [ ]:
x = x.reshape(2697 , 88 , 1)

In [ ]:
final.shape

(3372, 89)

In [ ]:
x = X.values.reshape(3372 , 88 , 1)

In [ ]:
model.fit(x, y_train, batch_size=12,epochs=50, verbose=1)

Epoch 1/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0037
Epoch 2/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0019
Epoch 3/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0016
Epoch 4/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0013
Epoch 5/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0013
Epoch 6/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0013
Epoch 7/50
225/225 [==============================] - 1s 3ms/step - loss: 0.0011
Epoch 8/50
225/225 [==============================] - 1s 4ms/step - loss: 0.0011
Epoch 9/50
225/225 [==============================] - 1s 4ms/step - loss: 9.7006e-04
Epoch 10/50
225/225 [==============================] - 1s 4ms/step - loss: 9.9483e-04
Epoch 11/50
225/225 [==============================] - 1s 4ms/step - loss: 9.9313e-04
Epoch 12/50
225/225 [==============================] - 1s 4ms/step - loss: 9.7361e-04
Epoch 13/

In [ ]:
X_test.shape

(675, 88)

In [ ]:
xx = X_test.values.reshape(675 , 88 , 1)

In [ ]:
pred = model.predict(xx)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test , pred)

0.8001462403763155

In [ ]:
#Pediatric

In [ ]:
from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error

In [ ]:
r2_score(y_test , pred) #Pediatric Test

0.8021451603550197

In [ ]:
mean_absolute_error(y_test , pred)

0.036929645796320326

In [ ]:
mean_squared_error(y_test , pred)

0.0027269285363783055

In [ ]:
#TRAIN

In [ ]:
Y_TRAIN_PRED = model.predict(x)

In [ ]:
r2_score(y_train , Y_TRAIN_PRED)

0.9161746885648828

In [ ]:
mean_absolute_error(y_train , Y_TRAIN_PRED)

0.026867893185875943

In [ ]:
mean_squared_error(y_train , Y_TRAIN_PRED)

0.001410701808318031

In [ ]:
#Geriatric

In [ ]:
pred = model.predict(xx)

In [ ]:
r2_score(y_test , pred) #Geriatric Test

0.8683610682968521

In [ ]:
mean_absolute_error(y_test , pred)

0.03274364186517317

In [ ]:
mean_squared_error(y_test , pred)

0.0019046860167884825

In [ ]:
#TRAIN

In [ ]:
Y_TRAIN_PRED = model.predict(x)

In [ ]:
r2_score(y_train , Y_TRAIN_PRED)

0.9332815382692157

In [ ]:
mean_absolute_error(y_train , Y_TRAIN_PRED)

0.024048306863519796

In [ ]:
mean_squared_error(y_train , Y_TRAIN_PRED)

0.0010648723653270955

In [ ]:
#HIV

In [ ]:
pred = model.predict(xx)

In [ ]:
r2_score(y_test , pred) # Test

0.9223469329487094

In [ ]:
mean_absolute_error(y_test , pred)

0.01868195429686608

In [ ]:
mean_squared_error(y_test , pred)

0.0008785819240478323

In [ ]:
#TRAIN

In [ ]:
Y_TRAIN_PRED = model.predict(x)

In [ ]:
r2_score(y_train , Y_TRAIN_PRED)

0.943461082858931

In [ ]:
mean_absolute_error(y_train , Y_TRAIN_PRED)

0.016374572095305434

In [ ]:
mean_squared_error(y_train , Y_TRAIN_PRED)

0.0007974943435311712

In [ ]:
model.summary()

Model: "sequential_19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_36 (Conv1D)           (None, 87, 32)            96        
_________________________________________________________________
flatten_13 (Flatten)         (None, 2784)              0         
_________________________________________________________________
dense_21 (Dense)             (None, 64)                178240    
_________________________________________________________________
dense_22 (Dense)             (None, 1)                 65        
Total params: 178,401
Trainable params: 178,401
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#----------------------------------------------------------------------

In [ ]:
test.head()

AGRA  AIZAWL  ALAPPUZHA  ...       so2        no2       rspm
0     1       0          0  ...  4.266817  19.016176  197.43720
1     1       0          0  ...  4.026891  20.378157  207.55490
2     1       0          0  ...  4.081528  20.484528  229.09227
3     1       0          0  ...  3.947581  18.359955  234.64357
4     1       0          0  ...  3.982175  18.168934  218.12114

[5 rows x 88 columns]

In [ ]:
test['Pediatric'] = 0
test['Geriatric'] = 0
test['HIV'] = 0

In [ ]:
scaler2 = MinMaxScaler()

In [ ]:
scaled_test = scalerX.fit_transform(test.values)

In [ ]:
scaled_test_df = pd.DataFrame(scaled_test , columns = test.columns)

In [ ]:
scaled_test_df

AGRA  AIZAWL  ALAPPUZHA  ...       so2       no2      rspm
0      1.0     0.0        0.0  ...  0.134334  0.004070  0.157650
1      1.0     0.0        0.0  ...  0.127081  0.004389  0.165605
2      1.0     0.0        0.0  ...  0.128733  0.004414  0.182538
3      1.0     0.0        0.0  ...  0.124684  0.003917  0.186902
4      1.0     0.0        0.0  ...  0.125730  0.003872  0.173912
...    ...     ...        ...  ...       ...       ...       ...
1843   0.0     0.0        0.0  ...  0.195765  0.002742  0.045873
1844   0.0     0.0        0.0  ...  0.192212  0.002640  0.044911
1845   0.0     0.0        0.0  ...  0.189371  0.002630  0.044244
1846   0.0     0.0        0.0  ...  0.186327  0.002632  0.043728
1847   0.0     0.0        0.0  ...  0.183259  0.002531  0.043108

[1848 rows x 88 columns]

In [ ]:
testing_df = scaled_test_df.drop(['Pediatric' , 'Geriatric' , 'HIV'] , axis = 1)

KeyError: ignored

In [ ]:
scaled_test_df.shape

(1848, 88)

In [ ]:
testing_df_reshape = scaled_test_df.values.reshape(1848 , 88 , 1)


In [ ]:
prediction = model.predict(testing_df_reshape)

In [ ]:
test['Geriatric'] = prediction

In [ ]:
test.head()

AGRA  AIZAWL  ALAPPUZHA  ...  Pediatric  Geriatric       HIV
0     1       0          0  ...   0.253501   0.034710 -0.063027
1     1       0          0  ...   0.295092   0.039801 -0.043142
2     1       0          0  ...   0.305647   0.036636 -0.043993
3     1       0          0  ...   0.273171   0.054650 -0.035694
4     1       0          0  ...   0.277577   0.051791 -0.035766

[5 rows x 91 columns]

In [ ]:
output = scaler2.inverse_transform(test.values)

In [ ]:
output_df = pd.DataFrame(output , columns = test.columns)

In [ ]:
output_df

AGRA  AIZAWL  ALAPPUZHA  ...  Pediatric  Geriatric       HIV
0      1.0     0.0        0.0  ...   0.253501   0.034710 -0.063027
1      1.0     0.0        0.0  ...   0.295092   0.039801 -0.043142
2      1.0     0.0        0.0  ...   0.305647   0.036636 -0.043993
3      1.0     0.0        0.0  ...   0.273171   0.054650 -0.035694
4      1.0     0.0        0.0  ...   0.277577   0.051791 -0.035766
...    ...     ...        ...  ...        ...        ...       ...
1843   0.0     0.0        0.0  ...   0.088242   0.132747  0.128345
1844   0.0     0.0        0.0  ...   0.069157   0.140036  0.080101
1845   0.0     0.0        0.0  ...   0.066820   0.153721  0.089671
1846   0.0     0.0        0.0  ...   0.069156   0.148101  0.098185
1847   0.0     0.0        0.0  ...   0.118642   0.159663  0.105572

[1848 rows x 91 columns]

In [ ]:
test

AGRA  AIZAWL  ALAPPUZHA  ...  Pediatric  Geriatric       HIV
0        1       0          0  ...   0.253501   0.034710 -0.063027
1        1       0          0  ...   0.295092   0.039801 -0.043142
2        1       0          0  ...   0.305647   0.036636 -0.043993
3        1       0          0  ...   0.273171   0.054650 -0.035694
4        1       0          0  ...   0.277577   0.051791 -0.035766
...    ...     ...        ...  ...        ...        ...       ...
1843     0       0          0  ...   0.088242   0.132747  0.128345
1844     0       0          0  ...   0.069157   0.140036  0.080101
1845     0       0          0  ...   0.066820   0.153721  0.089671
1846     0       0          0  ...   0.069156   0.148101  0.098185
1847     0       0          0  ...   0.118642   0.159663  0.105572

[1848 rows x 91 columns]

In [ ]:
test.head()

AGRA  AIZAWL  ALAPPUZHA  ...  Pediatric  Geriatric       HIV
0     1       0          0  ...   0.253501   0.034710 -0.063027
1     1       0          0  ...   0.295092   0.039801 -0.043142
2     1       0          0  ...   0.305647   0.036636 -0.043993
3     1       0          0  ...   0.273171   0.054650 -0.035694
4     1       0          0  ...   0.277577   0.051791 -0.035766

[5 rows x 91 columns]

In [ ]:
tttt = test.drop(['Pediatric' , 'Geriatric' , 'HIV'] , axis = 1)

In [ ]:
tttt.shape

(1848, 88)

In [ ]:
tttt = tttt.values.reshape(1848 , 88 , 1)

In [ ]:
pppp = model.predict(tttt)

In [ ]:
output = test

In [ ]:
output['HIV'] = pppp

In [ ]:
output.head(30)

AGRA  AIZAWL  ALAPPUZHA  ...  Pediatric  Geriatric        HIV
0      1       0          0  ...  26.582008  39.071129   9.886550
1      1       0          0  ...  29.340445  45.015896   3.839921
2      1       0          0  ...  30.008953  54.583042   0.221649
3      1       0          0  ...  23.115191  46.328091  16.930185
4      1       0          0  ...  27.867039  43.599972   7.595315
5      1       0          0  ...  28.473507  43.407070   3.687541
6      1       0          0  ...  28.940426  51.843121   1.842819
7      1       0          0  ...  23.362215  45.442455  18.223555
8      1       0          0  ...  27.103823  40.337780  11.430857
9      1       0          0  ...  28.432297  42.834270   4.707851
10     1       0          0  ...  26.072283  47.961636   4.694951
11     1       0          0  ...  21.561287  45.185760  17.818623
12     1       0          0  ...  26.418856  38.576778  13.424001
13     1       0          0  ...  27.291378  40.102352   9.329943
14     1       0          0  ...  24.415943  44.170902   9.368564
15     1       0          0  ...  20.284542  43.952118  18.789888
16     1       0          0  ...  25.612528  36.648464  13.279815
17     1       0          0  ...  26.132952  38.068172  12.341758
18     1       0          0  ...  21.872646  41.061428  12.910043
19     1       0          0  ...  19.019678  43.744637  18.764189
20     1       0          0  ...  24.442001  34.751087  12.871577
21     1       0          0  ...  24.575422  35.796543  12.488732
22     1       0          0  ...  20.349249  37.797024  12.726551
23     1       0          0  ...  17.795029  42.999355  19.376732
24     0       1          0  ...   3.913879   6.921444  10.308840
25     0       1          0  ...   0.988156  20.405918  34.257763
26     0       1          0  ...   5.145596  11.989069   8.838192
27     0       1          0  ...   4.787117  11.564236  15.171892
28     0       1          0  ...   2.343154  18.140980  31.486973
29     0       1          0  ...   2.274235  18.842522  32.112427

[30 rows x 91 columns]

In [ ]:
output.to_csv(r'Output.csv' , index = False)

In [ ]:
chachacha =  output.iloc[: , ['AGRA':'VISAKHAPATNAM']]

SyntaxError: ignored

In [ ]:
col = ['AGRA', 'AIZAWL', 'ALAPPUZHA', 'ALLAHABAD', 'ALWAR', 'AMRAVATI',
       'AMRITSAR', 'BATHINDA', 'BHARUCH', 'BHOPAL', 'BULANDSHAHR', 'CACHAR',
       'CHANDIGARH', 'CHENNAI', 'CHITTOOR', 'COIMBATORE', 'CUTTACK',
       'DAKSHINAKANNADA', 'DEHRADUN', 'DHANBAD', 'DIBRUGARH', 'DURG',
       'EASTKHASIHILLS', 'ERNAKULAM', 'FATEHGARHSAHIB', 'FIROZABAD', 'GANJAM',
       'GHAZIABAD', 'GOLAGHAT', 'GUNTUR', 'GWALIOR', 'HASSAN', 'INDORE',
       'JABALPUR', 'JAIPUR', 'JALANDHAR', 'JALGAON', 'JAMNAGAR', 'JHANSI',
       'JODHPUR', 'KANPURNAGAR', 'KOLHAPUR', 'KOLLAM', 'KORBA', 'KOTTAYAM',
       'KOZHIKODE', 'KURNOOL', 'LATUR', 'LUCKNOW', 'LUDHIANA', 'MADURAI',
       'MORADABAD', 'NAGPUR', 'NASHIK', 'NORTHGOA', 'PALAKKAD', 'PATIALA',
       'PUNE', 'RAJKOT', 'RANCHI', 'RAYAGADA', 'SAGAR', 'SALEM', 'SANGLI',
       'SIRMAUR', 'SOLAN', 'SOLAPUR', 'SONBHADRA', 'SONITPUR', 'SOUTHGOA',
       'SURAT', 'THANE', 'THIRUVANANTHAPURAM', 'VADODARA', 'VALSAD',
       'VARANASI', 'VISAKHAPATNAM']

In [ ]:
output.columns

Index(['AGRA', 'AIZAWL', 'ALAPPUZHA', 'ALLAHABAD', 'ALWAR', 'AMRAVATI',
       'AMRITSAR', 'BATHINDA', 'BHARUCH', 'BHOPAL', 'BULANDSHAHR', 'CACHAR',
       'CHANDIGARH', 'CHENNAI', 'CHITTOOR', 'COIMBATORE', 'CUTTACK',
       'DAKSHINAKANNADA', 'DEHRADUN', 'DHANBAD', 'DIBRUGARH', 'DURG',
       'EASTKHASIHILLS', 'ERNAKULAM', 'FATEHGARHSAHIB', 'FIROZABAD', 'GANJAM',
       'GHAZIABAD', 'GOLAGHAT', 'GUNTUR', 'GWALIOR', 'HASSAN', 'INDORE',
       'JABALPUR', 'JAIPUR', 'JALANDHAR', 'JALGAON', 'JAMNAGAR', 'JHANSI',
       'JODHPUR', 'KANPURNAGAR', 'KOLHAPUR', 'KOLLAM', 'KORBA', 'KOTTAYAM',
       'KOZHIKODE', 'KURNOOL', 'LATUR', 'LUCKNOW', 'LUDHIANA', 'MADURAI',
       'MORADABAD', 'NAGPUR', 'NASHIK', 'NORTHGOA', 'PALAKKAD', 'PATIALA',
       'PUNE', 'RAJKOT', 'RANCHI', 'RAYAGADA', 'SAGAR', 'SALEM', 'SANGLI',
       'SIRMAUR', 'SOLAN', 'SOLAPUR', 'SONBHADRA', 'SONITPUR', 'SOUTHGOA',
       'SURAT', 'THANE', 'THIRUVANANTHAPURAM', 'VADODARA', 'VALSAD',
       'VARANASI', 'VISAKHAPATNAM', 'year

In [ ]:
akbfak = output.drop(['year', 'month', 'Rainfall',
       'Relative Humidity', 'Average Temperature', 'NSP Total',
       'Relapse Total', 'NSN Total', 'so2', 'no2', 'rspm', 'Pediatric',
       'Geriatric', 'HIV'] , axis = 1)

In [ ]:
qtr4 = output[output['month'] == 4]

In [ ]:
pedsum = qtr4['Pediatric'].sum()

In [ ]:
pedsum

5464.035

In [ ]:
gersum = qtr4['Geriatric'].sum()

In [ ]:
hivsum = qtr4['HIV'].sum()

In [ ]:
pedsum

5464.035

In [ ]:
gersum

23140.2

In [ ]:
hivsum

5929.6255

In [ ]:
qtr4

AGRA  AIZAWL  ALAPPUZHA  ...  Pediatric   Geriatric        HIV
3        1       0          0  ...  23.115191   46.328091  16.930185
7        1       0          0  ...  23.362215   45.442455  18.223555
11       1       0          0  ...  21.561287   45.185760  17.818623
15       1       0          0  ...  20.284542   43.952118  18.789888
19       1       0          0  ...  19.019678   43.744637  18.764189
...    ...     ...        ...  ...        ...         ...        ...
1831     0       0          0  ...  18.570595   85.760948  82.444626
1835     0       0          0  ...  19.128477   89.396904  81.604904
1839     0       0          0  ...  20.825191   90.189346  81.711685
1843     0       0          0  ...  21.437990   95.072792  81.027328
1847     0       0          0  ...  22.331425  100.330070  79.734879

[462 rows x 91 columns]

In [ ]:
prediction

array([[0.16020715],
       [0.17090733],
       [0.20852023],
       ...,
       [0.10938267],
       [0.10032634],
       [0.09417877]], dtype=float32)

In [ ]:
pred = scalerY.inverse_transform(prediction)

In [ ]:
pred

array([[169.20198],
       [179.63466],
       [216.30724],
       ...,
       [119.64811],
       [110.81819],
       [104.8243 ]], dtype=float32)

In [ ]:
test['NEP Total'] = pred

In [ ]:
test

AGRA  AIZAWL  ALAPPUZHA  ...        rspm   NEP Total  Total Cases
0        1       0          0  ...  197.437200  169.201981  1178.834241
1        1       0          0  ...  207.554900  179.634659  1352.396649
2        1       0          0  ...  229.092270  216.307236  1307.519306
3        1       0          0  ...  234.643570  179.527496  1081.886956
4        1       0          0  ...  218.121140  167.708054  1152.208224
...    ...     ...        ...  ...         ...         ...          ...
1843     0       0          0  ...   55.265408  119.077682  1481.133932
1844     0       0          0  ...   54.041416  149.590240  1594.353010
1845     0       0          0  ...   53.193733  119.648109  1643.797519
1846     0       0          0  ...   52.537240  110.818192  1551.956462
1847     0       0          0  ...   51.748238  104.824303  1523.688443

[1848 rows x 90 columns]

In [ ]:
test['Total Cases'] = test['NSP Total'] + test['Relapse Total'] + test['NSN Total'] + test['NEP Total']

In [ ]:
test.to_csv('OutputWithTotalCases.csv' , index = False)